services:
  gateway:
    build: 
      context: .          
      dockerfile: Dockerfile.gateway
    user: "1001:1001"     
    ports:
      - "127.0.0.1:8000:8000"
    env_file: .env
    volumes:
      - frakt_sockets:/tmp/sockets
      - ./logs:/app/logs            
    depends_on:
      - worker
  worker:
    build: 
      context: ./worker  
      dockerfile: Dockerfile.worker
    user: "1002:1001"  
    volumes:
      - frakt_sockets:/tmp/sockets
volumes:
  frakt_sockets:
    driver: local
    driver_opts:
      type: tmpfs      
      device: tmpfs